### ISSUE TITLE
will this model recognizes line text , if so , how to use this model for line htr?

### ISSUE THREAD

**Issue by Tprasanthi** [dmitrijsk/AttentionHTR#6]
could you reply me on this?

**Comment by ektavats** [comment]
Hi! This model performs recognition only at the word level. For line HTR, you will need to first perform line detection and then use a text detection algorithm to segment the line into individual words. For instance, you can explore Faster R-CNN. After this, you can proceed with AttentionHTR for word recognition.

**Comment by Tprasanthi** [comment]
Thank you very much , for your response.
